version: '3.8'
services:
  mydatabase:
    env_file:
      - .env
    image: postgres:13
    ports:
      - "5432:5432"
      # - ${DB_PORT}:5432
      # 5432 seems default
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - restful
networks:
  restful:
